name: learning-github-actions
run-name: Test by ${{ github.actor }}
on: [push]
jobs:
  setup-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      #- run: npm install -g bats
      #- run: bats -v
      - name: docker run test
        run: sudo apt-get install docker
          sudo docker pull hello-world
          docker run hello-world
